#!/usr/bin/env python3
"""Assemble recorded human reactions and matching mouth envelopes. Requires FFmpeg.

Usage: python3 tools/build_jack_reactions.py --ffmpeg /path/to/ffmpeg
No synthesis, pitch shifting, or time stretching is used.
"""
import argparse
import array
import math
from pathlib import Path
import subprocess
import tempfile
import wave

ROOT = Path(__file__).resolve().parents[1]
RATE = 24000
DURATION = 13.5


def decode(ffmpeg, path, directory):
    output = directory / (path.stem + '.wav')
    subprocess.run([ffmpeg, '-y', '-loglevel', 'error', '-i', str(path),
                    '-ac', '1', '-ar', str(RATE), str(output)], check=True)
    with wave.open(str(output)) as stream:
        return [x / 32768 for x in array.array('h', stream.readframes(stream.getnframes()))]


def prepare(samples, start, end, peak, tail=.035):
    samples = samples[round(start * RATE):round(end * RATE)]
    gain = peak / max(abs(x) for x in samples)
    return [x * gain * min(1, i / (RATE * .012), (len(samples)-1-i) / (RATE * tail))
            for i, x in enumerate(samples)]


def envelope(samples):
    # 30 ms window centered on each 10 ms sample. Ignore the low reverb tail,
    # so the face does not keep talking after the performer has stopped.
    values = []
    for offset in range(0, len(samples) + 480, 240):
        window = samples[max(0, offset - 360):min(len(samples), offset + 360)]
        rms = math.sqrt(sum(x*x for x in window) / max(1, len(window)))
        values.append(min(1, max(0, (rms - .025) / .18) ** .70))
    return values


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ffmpeg', default='ffmpeg')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as temp:
        directory = Path(temp)
        organ = decode(args.ffmpeg, ROOT / 'tools/audio-sources/dramatic-organ-inspectorj.mp3', directory)
        reaction = decode(args.ffmpeg, ROOT / 'tools/audio-sources/boo-and-laugh-metrostock99.mp3', directory)
    # Preserve the complete Boo/laugh recording and its natural pause.
    reaction = prepare(reaction, .48, 3.50, .72, tail=.12)
    track = [0.] * round(DURATION * RATE)
    for start, samples in [(5.82, reaction)]:
        for i, sample in enumerate(samples):
            track[round(start * RATE) + i] += sample
    output = ROOT / 'src/PumpkinFace.Display/Assets/Audio/jack-playful-scare.wav'
    with wave.open(str(output), 'wb') as stream:
        stream.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        stream.writeframes(array.array('h', [round(max(-.98, min(.98, x)) * 32767) for x in track]).tobytes())
    # Independent short clips retain the exact placement used by PerformanceLibrary.
    for name, duration, offset, samples in [
        ('boo', 2.7, .82, prepare(reaction, 0, 1.15, .72, tail=.04)),
        ('chuckle', 3.5, .30, reaction[round(1.18 * RATE):]),
        ('haunted-organ', 20, 0, prepare(organ, 0, min(19.9, len(organ)/RATE), .72, tail=.35)),
    ]:
        clip = [0.] * round(duration * RATE)
        start = round(offset * RATE)
        clip[start:start + len(samples)] = samples
        with wave.open(str(output.parent / (name + '.wav')), 'wb') as stream:
            stream.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
            stream.writeframes(array.array('h', [round(x * 32767) for x in clip]).tobytes())
    # Mouth roles split at a quiet moment in the original uninterrupted recording.
    # Each envelope is measured from the final PCM, including applied gain/fades.
    with wave.open(str(output)) as stream:
        pcm = [x / 32768 for x in array.array('h', stream.readframes(stream.getnframes()))]
    cues = [('Boo', 5.82, 6.97, .27, .95),
            ('Laugh', 7.00, 8.84, .74, .10)]
    source = ['namespace PumpkinFace.Core;', '',
              '// Generated by tools/build_jack_reactions.py from recorded human vocals.',
              '// 10 ms RMS envelopes measured from the bundled PCM; see Assets/Audio/README.md.',
              'internal static class JackVocalTrack', '{',
              '    internal enum Reaction { Boo, Laugh }',
              '    internal sealed record Cue(Reaction Kind, double Start, float Width, float Roundness, float[] Energy);',
              '    internal static readonly Cue[] Cues =', '    [']
    for kind, start, end, width, roundness in cues:
        energy = envelope(pcm[round(start * RATE):round(end * RATE)])
        source.append(f'        new(Reaction.{kind}, {start}, {width}f, {roundness}f, [')
        for i in range(0, len(energy), 15):
            source.append('            ' + ', '.join(f'{x:.3f}f' for x in energy[i:i+15]) + ',')
        source.append('        ]),')
    source.extend(['    ];', '}', ''])
    (ROOT / 'src/PumpkinFace.Core/JackVocalTrack.cs').write_text('\n'.join(source))
    print(f'Wrote {output} and matching envelopes; peak {max(abs(x) for x in track):.3f}.')


if __name__ == '__main__':
    main()
