#!/usr/bin/env python3
"""Prepare Vader breathing, a saber ignition/hum/shutdown, and a breath-only motion envelope.

Usage: python3 tools/build_vader_performance.py --ffmpeg /path/to/ffmpeg
Source and license: src/PumpkinFace.Display/Assets/Audio/README.md
"""
import argparse
import array
import math
from pathlib import Path
import tempfile
import wave

from build_jack_reactions import ROOT, RATE, decode, prepare

DURATION = 13.5


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ffmpeg', default='ffmpeg')
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as temp:
        samples = decode(args.ffmpeg, ROOT / 'tools/audio-sources/vader-breathing-ihitokage.mp3', Path(temp))
        ignition = decode(args.ffmpeg, ROOT / 'tools/audio-sources/lightsaber-ignition-pip.mp3', Path(temp))
    # Two breathing cycles, preserving their recorded pacing, with a quiet exit.
    breath = prepare(samples, 0, 11.9, .72, tail=.4)
    breath = [value * min(1, i / (RATE * .12)) for i, value in enumerate(breath)]
    track = [0.] * round(DURATION * RATE)
    start = round(.65 * RATE)
    track[start:start + len(breath)] = breath
    pcm = array.array('h', [round(value * 32767) for value in track])
    # Keep motion tied to breathing, not to the louder saber sound effects.
    breath_pcm = pcm
    ignition = prepare(ignition, 0, len(ignition) / RATE, .52, tail=.16)
    shutdown = prepare(list(reversed(ignition[:round(.65 * RATE)])), 0, .65, .36, tail=.10)
    for offset, effect in [(3.25, ignition), (10.4, shutdown)]:
        for i, value in enumerate(effect):
            target = round(offset * RATE) + i
            if target < len(track):
                track[target] += value
    def smooth(value):
        value = min(1, max(0, value))
        return value * value * (3 - 2 * value)
    for i in range(round(3.25 * RATE), round(10.95 * RATE)):
        time = i / RATE
        gate = smooth((time - 3.25) / .32) * (1 - smooth((time - 10.4) / .55))
        # Original low electrical drone, smoothly enveloped with the blade glow.
        hum = .040 * math.sin(math.tau * 60 * time) + .028 * math.sin(math.tau * 120 * time) + .012 * math.sin(math.tau * 180 * time)
        track[i] += hum * gate
    gain = min(1, .92 / max(abs(value) for value in track))
    pcm = array.array('h', [round(value * gain * 32767) for value in track])
    output = ROOT / 'src/PumpkinFace.Display/Assets/Audio/vader-entrance.wav'
    with wave.open(str(output), 'wb') as stream:
        stream.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        stream.writeframes(pcm.tobytes())

    # A 120 ms energy window smooths the breath into subtle movement, not jaw chatter.
    energy = []
    for offset in range(0, len(breath_pcm) + 1, RATE // 50):
        window = breath_pcm[max(0, offset - 1440):min(len(breath_pcm), offset + 1440)]
        rms = math.sqrt(sum((x / 32768)**2 for x in window) / max(1, len(window)))
        energy.append(min(1, max(0, (rms - .012) / .13)))
    source = ['namespace PumpkinFace.Core;', '',
              '// Generated by tools/build_vader_performance.py from the isolated breathing PCM.',
              'internal static class VaderBreathTrack', '{',
              '    internal const int SamplesPerSecond = 50;',
              '    internal static readonly float[] Energy =', '    [']
    for i in range(0, len(energy), 15):
        source.append('        ' + ', '.join(f'{value:.3f}f' for value in energy[i:i+15]) + ',')
    source.extend(['    ];', '}', ''])
    (ROOT / 'src/PumpkinFace.Core/VaderBreathTrack.cs').write_text('\n'.join(source))
    assert len(pcm) == round(DURATION * RATE)
    assert not any(pcm[:start]) and not any(pcm[round(12.7 * RATE):])
    print(f'Wrote {output} and {len(energy)} synchronized energy samples.')


if __name__ == '__main__':
    main()
